Dev
engaging-computing/MYR-backend pull request #251
Opened 2021-08-20 15:13 UTC by Joshua119

2021-08-20 15:19 UTC, kdvalin submitted a review, later dismissed

2021-08-20 15:33 UTC, Jlu18 requested changes

2021-08-20 15:33 UTC, Jlu18 commented on public/about/team/index.html
>          <div class="card info-card bg-light col-lg-5 col-sm-12 mr-auto col-centered border-0 "></div>
replace this line with \</div\> to format your card.

2021-08-20 15:35 UTC, Jlu18 commented on public/about/team/index.html
>          <div class="card info-card bg-light col-lg-5 col-sm-12 mr-auto col-centered border-0 "></div>
![2021-08-20-113426_1197x515_scrot](https://user-images.githubusercontent.com/50334618/130257722-c3371fd7-f702-4ec6-8c9b-a5150db17048.png)

2021-11-16 01:20 UTC, kdvalin approved these changes

2021-11-16 01:21 UTC, merged